### ISSUE TITLE
flip method in my-detection.py freezed video

### ISSUE THREAD

**Issue by HerrAskinSM** [dusty-nv/jetson-inference#1255]
> `--flip-method=rotate-180` is a command line argument to the detectnet/imagenet/segnet/video-viewer sample programs.
> 
> If you wanted to add support for this argument to `my-detection.py`, change the videoSource line to:
> 
> ```python
> import sys
> camera = jetson.utils.videoSource("csi://0", argv=sys.argv)
> ```

Hi, Dustin!
I made changes to the file, but when running the program "python 3 my-detection.py --input-flip=rotate-180" the picture from the camera freezes.

command: video-viewer --input-flip=rotate-180
return
"video-viewer:  failed to capture video frame
[gstreamer] gstDecoder -- failed to retrieve next image buffer
video-viewer:  failed to capture video frame"

**Comment by pjreed** [comment]
This is also an issue for me.  If I try running `video-viewer csi://0 rtp://192.168.2.98:8008 --input-flip=none`, I get a single flipped frame, but then the stream stops and I never get any more frames.  I have to reboot my Jetson in order for the camera to work again.

**Comment by dusty-nv** [comment]
Hi @pjreed, can you see if the issue is related to NVMM memory by trying the following:

``` bash
cd /path/to/your/jetson-inference/build
cmake -DDISABLE_NVMM ../
make
sudo make install
```

Or instead clone/build/install the `nvmm-disabled` branch:  https://github.com/dusty-nv/jetson-inference/tree/nvmm-disabled

**Comment by pjreed** [comment]
That cmake command fails with:
```
cmake .. -DDISABLE_NVMM
Parse error in command line argument: -DDISABLE_NVMM
Should be: VAR:type=value
CMake Error: No cmake script provided.
CMake Error: Problem processing arguments. Aborting.
```

I tried `-DDISABLE_NVMM=1` instead, but I don't see any difference; it still locks up after one from.

I tried checking out the `nvmm-disabled` branch, and the build fails with:

```
[ 68%] Linking CXX shared library aarch64/lib/libjetson-inference.so
/usr/bin/ld: cannot find -lnvbuf_utils
collect2: error: ld returned 1 exit status
CMakeFiles/jetson-inference.dir/build.make:1519: recipe for target 'aarch64/lib/libjetson-inference.so' failed
make[2]: *** [aarch64/lib/libjetson-inference.so] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jetson-inference.dir/all' failed
make[1]: *** [CMakeFiles/jetson-inference.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

I'm not entirely sure why that would fail; I checked and I do have that library at `/usr/lib/aarch64-linux-gnu/tegra/libnvbuf_utils.so`, and the `master` branch builds fine...

**Comment by dusty-nv** [comment]
> That cmake command fails with:
> 
> ```
> cmake .. -DDISABLE_NVMM
> Parse error in command line argument: -DDISABLE_NVMM
> Should be: VAR:type=value
> CMake Error: No cmake script provided.
> CMake Error: Problem processing arguments. Aborting.
> ```

OK, sorry about that - I just fixed this in https://github.com/dusty-nv/jetson-utils/commit/0d3f59f5c0967a108ec1cd58a518ee5ad817d35b

Please re-clone or pull the latest master, then run:

``` bash
cd /path/to/your/jetson-inference/build
cmake -DENABLE_NVMM=OFF ../
make
sudo make install
```

**Comment by pjreed** [comment]
I rebuilt using the latest master and that flag, and the behavior is slightly different, but still not fixed.  Now I do not see any frames at all; `video-viewer`'s output just before it fails looks like:

```
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> mysource
nvbuf_utils: dmabuf_fd 1030 mapped entry NOT found                 
nvbuf_utils: Can not get HW buffer from FD... Exiting...              
NvBufferGetParams failed for dst_dmabuf_fd                                  
nvbuffer_transform Failed                                           
[gstreamer] gstEncoder -- new caps: video/x-raw, width=1280, height=720, format=(string)I420, framerate=30/1
Framerate set to : 30 at NvxVideoEncoderSetParameterNvMMLiteOpen : Block : BlockType = 4
===== NVMEDIA: NVENC =====                                              
NvMMLiteBlockCreate : Block : BlockType = 4       
video-viewer:  captured 2 frames (1280 x 720)                                 
H264: Profile = 66, Level = 40                                                                                             
NVMEDIA_ENC: bBlitMode is set to TRUE            
[gstreamer] gstreamer stream status CREATE ==> src                                                                         
[gstreamer] gstreamer stream status ENTER ==> src                                  
[gstreamer] gstreamer message stream-start ==> pipeline1           
[gstreamer] gstreamer changed state from READY to PAUSED ==> udpsink0  
[gstreamer] gstreamer message async-done ==> pipeline1                    
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> udpsink0         
[gstreamer] gstreamer changed state from PAUSED to PLAYING ==> pipeline1    
[gstreamer] gstDecoder -- failed to retrieve next image buffer
video-viewer:  failed to capture video frame                               
[gstreamer] gstDecoder -- failed to retrieve next image buffer                                                             
video-viewer:  failed to capture video frame
```

On the up side, it does not seem to break the camera until reboot any more; re-running the command without `--input-flip=rotate-180` works fine.

**Comment by dusty-nv** [comment]
> nvbuf_utils: dmabuf_fd 1030 mapped entry NOT found                 
> nvbuf_utils: Can not get HW buffer from FD... Exiting...              
> NvBufferGetParams failed for dst_dmabuf_fd                                  
> nvbuffer_transform Failed

Hmm I don't believe this should be here if `-DENABLE_NVMM=OFF` was set

**Comment by pjreed** [comment]
Actually, scratch what I just said -- I realized I did a `git pull` on the `jetson-inference` repo but did not also update the `utils` submodule.  After update that and rebuilding, now it works!

**Comment by dusty-nv** [comment]
OK cool, thanks!

What MIPI CSI camera are you using btw?

**Comment by pjreed** [comment]
This is with a SainSmart IMX219: https://www.sainsmart.com/products/sainsmart-imx219-camera-module-for-nvidia-jetson-nano-board-8mp-sensor-160-degree-fov
