### ISSUE TITLE
How to reduce framerate of videoSource

### ISSUE THREAD

**Issue by nithinpremkumar1999** [dusty-nv/jetson-inference#1656]
Hi I am running multiple models at the same time and I do not require the video stream to be very fast. For my use case below 30 fps is more than enough to save resources.
I have tried to change frame rate using this in my custom function:
camera = videoSource(argv=["input=v4l2:///dev/video0", "--framerate=20"])
But this doesn't change the frame rate for some reason. Any help would be greatly appreciated.

System: Jetson Nano, JetPack 4.6.1, Ubuntu 18.04
Language: Python

@dusty-nv

**Comment by dusty-nv** [comment]
Hi @nithinpremkumar1999, this should be fixed in https://github.com/dusty-nv/jetson-utils/commit/2ded2cec9de416ecc9e9c5a69f7010593d86817d

Can you try again after updating your jetson-inference?

``` bash
cd jetson-inference
git pull --recurse-submodules
cd build
cmake ../
make
sudo make install
```

**Comment by nithinpremkumar1999** [comment]
Hi @dusty-nv, I updated my jetson-inference and it still does not seem to work. Is there any way I can skip frames in detectnet like in actionnet? Or how do I force the videosource to be a certain fps?
I have attached my console log to this comment for the error I get.
![MicrosoftTeams-image (4)](https://github.com/dusty-nv/jetson-inference/assets/70209031/52a73794-1d42-4d1b-8f5a-33ea9111836a)
![MicrosoftTeams-image (5)](https://github.com/dusty-nv/jetson-inference/assets/70209031/cb24e5a2-0581-4fa8-b413-7a4fc9216f8e)
The timeout kept on going for a few minutes so I force-stopped it.

**Comment by dusty-nv** [comment]
@nithinpremkumar1999 can you creating your video source like this:

``` python
camera = videoSource("/dev/video0", argv=["--input-rate=20"])
```

If you still get the timeouts, try it with `argv=["--input-rate=20", "--input-decoder=cpu"]` and please post the text of the console log here (I need to see when it starts to see your camera formats and the GStreamer pipeline that it creates)

You can also manually skip frames by just keeping track of the frame count and using modulus operator, or by using a timing function (like `time.perf_counter()` and `time.sleep()`)

**Comment by KorechiZifan** [comment]
This works for me.
```
camera = videoSource("/dev/video0", argv=["--framerate=20"])
```
The Same Ubuntu system, Jetpack, Nano, as the questioner.
Note: Nework FPS on the title is a different thing.

You may need to check your camera has this 20 fps option for you of specific size.
Try command:
```
$ v4l2-ctl -d0 --list-formats-ext
```
if you don't have v4l2-ctl, sudo apt-get install v4l-utils
Then my case (our default gstCamera can change from 5fps to 30fps):
" ioctl: xxxxxxxxxx (I hide it)
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.040s (25.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
Other Size... "

Try command:
```
$ gst-launch-1.0 v4l2src do-timestamp=true device=/dev/video0 ! image/jpeg,width=1280,height=720, framerate=5/1 ! jpegdec ! videoconvert ! xvimagesink sync=false
```
framerate= 30/1, 20/1, 5/1, you can do some experiment and see the difference.

Then finally I changed this line of code:
camera = videoSource("/dev/video0", argv=["--framerate=20"])

The output info does change to 20 when you run the demo program:
------------------------------------------------
gstCamera video options:
------------------------------------------------
  -- URI: v4l2:///dev/video0
     - protocol:  v4l2
     - location:  /dev/video0
  -- deviceType: v4l2
  -- ioType:     input
  -- codec:      MJPEG
  -- codecType:  cpu
  -- width:      1280
  -- height:     720
  -- frameRate:  20
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
------------------------------------------------

**Comment by KorechiZifan** [comment]
This works for me.
```
camera = videoSource("/dev/video0", argv=["--framerate=20"])
```
The Same Ubuntu system, Jetpack, Nano, as the questioner.
Note: Network FPS on the title is a different thing.

You may need to check your camera has this 20 fps option for you of specific size.
Try command:
```
$ v4l2-ctl -d0 --list-formats-ext
```
if you don't have v4l2-ctl, 
```
sudo apt-get install v4l-utils
```
Then my case (our default gstCamera can change from 5fps to 30fps for 1280x720):
" ioctl: VIDIOC_ENUM_FMT
	Index       : 0
	Type        : Video Capture
	Pixel Format: 'MJPG' (compressed)
	Name        : Motion-JPEG
Size: Discrete 1280x720
			Interval: Discrete 0.033s (30.000 fps)
			Interval: Discrete 0.040s (25.000 fps)
			Interval: Discrete 0.050s (20.000 fps)
			Interval: Discrete 0.067s (15.000 fps)
			Interval: Discrete 0.100s (10.000 fps)
			Interval: Discrete 0.200s (5.000 fps)
Other Size... "

Try command:
```
$ gst-launch-1.0 v4l2src do-timestamp=true device=/dev/video0 ! image/jpeg,width=1280,height=720, framerate=5/1 ! jpegdec ! videoconvert ! xvimagesink sync=false
```
Try change the framerate to **30/1, 20/1, 5/1**, you can do some experiments and see the difference. I tried 30 or 20 instead of 30/1 20/1 but errors are produced.

Finally I changed this line of code to:
camera = videoSource("/dev/video0", argv=["--framerate=20"])


The output info does change to 20 when you run the demo program:

gstCamera video options:
  -- URI: v4l2:///dev/video0
     - protocol:  v4l2
     - location:  /dev/video0
  -- deviceType: v4l2
  -- ioType:     input
  -- codec:      MJPEG
  -- codecType:  cpu
  -- width:      1280
  -- height:     720
  **-- frameRate:  20**
  -- numBuffers: 4
  -- zeroCopy:   true
  -- flipMethod: none
